apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ihcx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ihcx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0016-app
  name: devfile-sample-ihcx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ihcx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ihcx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-ihcx@sha256:be09a15065d396af86d012b6d9f3353de4e9d47db66bb868ec8cb19d4eb4403e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
